vae:
  latent_dim: 20
  epochs: 10
  lr: 0.001
  output_dir: './data/vae_outputs'
  model_save_path: './models/vae/vae_bbox_model.pth'

gan:
  batch_size: 64
  epochs: 100
  lr: 0.0002
  model_dir: './models/gan'
  synthetic_dir: './data/synthetic_data'
  augmented_dir: './data/augmented_data'

ocr:
  data_dir: './data/augmented_data'
  batch_size: 64
  epochs: 100
  lr: 0.001
  num_classes: 10
  model_save_path: './models/ocr/ocr_model.pth'
